"""initial_schema

Revision ID: bcae68216962
Revises: 
Create Date: 2026-05-03 13:19:31.895483
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bcae68216962'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('environment_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_environment_type'), 'environments', ['environment_type'], unique=False)
    op.create_index(op.f('ix_environments_id'), 'environments', ['id'], unique=False)
    op.create_index(op.f('ix_environments_status'), 'environments', ['status'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('node_type', sa.String(length=48), nullable=False),
    sa.Column('role', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('os_name', sa.String(length=120), nullable=True),
    sa.Column('os_version', sa.String(length=180), nullable=True),
    sa.Column('agent_version', sa.String(length=40), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('allocated_cpu_cores', sa.Integer(), nullable=True),
    sa.Column('allocated_ram_mb', sa.Integer(), nullable=True),
    sa.Column('max_cpu_cores', sa.Integer(), nullable=True),
    sa.Column('max_ram_mb', sa.Integer(), nullable=True),
    sa.Column('disk_total_gb', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_environment_id'), 'nodes', ['environment_id'], unique=False)
    op.create_index(op.f('ix_nodes_id'), 'nodes', ['id'], unique=False)
    op.create_index(op.f('ix_nodes_node_type'), 'nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_nodes_role'), 'nodes', ['role'], unique=False)
    op.create_index(op.f('ix_nodes_status'), 'nodes', ['status'], unique=False)
    op.create_table('agent_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('token_preview', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tokens_node_id'), 'agent_tokens', ['node_id'], unique=False)
    op.create_index(op.f('ix_agent_tokens_token_hash'), 'agent_tokens', ['token_hash'], unique=True)
    op.create_table('capacity_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=80), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('predicted_threshold_time', sa.DateTime(), nullable=True),
    sa.Column('trend_direction', sa.String(length=32), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capacity_forecasts_created_at'), 'capacity_forecasts', ['created_at'], unique=False)
    op.create_index(op.f('ix_capacity_forecasts_id'), 'capacity_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_capacity_forecasts_metric_name'), 'capacity_forecasts', ['metric_name'], unique=False)
    op.create_index(op.f('ix_capacity_forecasts_node_id'), 'capacity_forecasts', ['node_id'], unique=False)
    op.create_table('diagnostics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('diagnosis_type', sa.String(length=80), nullable=False),
    sa.Column('root_cause', sa.String(length=160), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostics_created_at'), 'diagnostics', ['created_at'], unique=False)
    op.create_index(op.f('ix_diagnostics_diagnosis_type'), 'diagnostics', ['diagnosis_type'], unique=False)
    op.create_index(op.f('ix_diagnostics_id'), 'diagnostics', ['id'], unique=False)
    op.create_index(op.f('ix_diagnostics_node_id'), 'diagnostics', ['node_id'], unique=False)
    op.create_index(op.f('ix_diagnostics_severity'), 'diagnostics', ['severity'], unique=False)
    op.create_index(op.f('ix_diagnostics_status'), 'diagnostics', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=60), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_environment_id'), 'reports', ['environment_id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_node_id'), 'reports', ['node_id'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_table('resource_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=True),
    sa.Column('cpu_core_count', sa.Integer(), nullable=True),
    sa.Column('load_average_1m', sa.Float(), nullable=True),
    sa.Column('load_average_5m', sa.Float(), nullable=True),
    sa.Column('load_average_15m', sa.Float(), nullable=True),
    sa.Column('ram_total_mb', sa.Float(), nullable=True),
    sa.Column('ram_used_mb', sa.Float(), nullable=True),
    sa.Column('ram_usage_percent', sa.Float(), nullable=True),
    sa.Column('ram_available_mb', sa.Float(), nullable=True),
    sa.Column('swap_total_mb', sa.Float(), nullable=True),
    sa.Column('swap_used_mb', sa.Float(), nullable=True),
    sa.Column('swap_usage_percent', sa.Float(), nullable=True),
    sa.Column('disk_total_gb', sa.Float(), nullable=True),
    sa.Column('disk_used_gb', sa.Float(), nullable=True),
    sa.Column('disk_usage_percent', sa.Float(), nullable=True),
    sa.Column('disk_read_bytes', sa.Float(), nullable=True),
    sa.Column('disk_write_bytes', sa.Float(), nullable=True),
    sa.Column('disk_read_rate', sa.Float(), nullable=True),
    sa.Column('disk_write_rate', sa.Float(), nullable=True),
    sa.Column('network_bytes_sent', sa.Float(), nullable=True),
    sa.Column('network_bytes_recv', sa.Float(), nullable=True),
    sa.Column('network_sent_rate', sa.Float(), nullable=True),
    sa.Column('network_recv_rate', sa.Float(), nullable=True),
    sa.Column('process_count', sa.Integer(), nullable=True),
    sa.Column('uptime_seconds', sa.Float(), nullable=True),
    sa.Column('temperature_celsius', sa.Float(), nullable=True),
    sa.Column('service_latency_ms', sa.Float(), nullable=True),
    sa.Column('service_error_rate', sa.Float(), nullable=True),
    sa.Column('custom_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_metrics_id'), 'resource_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_resource_metrics_node_id'), 'resource_metrics', ['node_id'], unique=False)
    op.create_index(op.f('ix_resource_metrics_timestamp'), 'resource_metrics', ['timestamp'], unique=False)
    op.create_table('simulation_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('scenario_type', sa.String(length=80), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_scenarios_environment_id'), 'simulation_scenarios', ['environment_id'], unique=False)
    op.create_index(op.f('ix_simulation_scenarios_id'), 'simulation_scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_scenarios_scenario_type'), 'simulation_scenarios', ['scenario_type'], unique=False)
    op.create_index(op.f('ix_simulation_scenarios_status'), 'simulation_scenarios', ['status'], unique=False)
    op.create_index(op.f('ix_simulation_scenarios_target_node_id'), 'simulation_scenarios', ['target_node_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('diagnostic_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('incident_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('root_cause', sa.String(length=160), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['diagnostic_id'], ['diagnostics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_diagnostic_id'), 'incidents', ['diagnostic_id'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_incident_type'), 'incidents', ['incident_type'], unique=False)
    op.create_index(op.f('ix_incidents_node_id'), 'incidents', ['node_id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_started_at'), 'incidents', ['started_at'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('diagnostic_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('current_cpu_cores', sa.Integer(), nullable=True),
    sa.Column('recommended_cpu_cores', sa.Integer(), nullable=True),
    sa.Column('current_ram_mb', sa.Integer(), nullable=True),
    sa.Column('recommended_ram_mb', sa.Integer(), nullable=True),
    sa.Column('expected_effect', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('action_steps_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['diagnostic_id'], ['diagnostics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_created_at'), 'recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_diagnostic_id'), 'recommendations', ['diagnostic_id'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_node_id'), 'recommendations', ['node_id'], unique=False)
    op.create_index(op.f('ix_recommendations_priority'), 'recommendations', ['priority'], unique=False)
    op.create_index(op.f('ix_recommendations_recommendation_type'), 'recommendations', ['recommendation_type'], unique=False)
    op.create_index(op.f('ix_recommendations_status'), 'recommendations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_status'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_recommendation_type'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_priority'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_node_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_diagnostic_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_created_at'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_started_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_node_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_type'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_diagnostic_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_simulation_scenarios_target_node_id'), table_name='simulation_scenarios')
    op.drop_index(op.f('ix_simulation_scenarios_status'), table_name='simulation_scenarios')
    op.drop_index(op.f('ix_simulation_scenarios_scenario_type'), table_name='simulation_scenarios')
    op.drop_index(op.f('ix_simulation_scenarios_id'), table_name='simulation_scenarios')
    op.drop_index(op.f('ix_simulation_scenarios_environment_id'), table_name='simulation_scenarios')
    op.drop_table('simulation_scenarios')
    op.drop_index(op.f('ix_resource_metrics_timestamp'), table_name='resource_metrics')
    op.drop_index(op.f('ix_resource_metrics_node_id'), table_name='resource_metrics')
    op.drop_index(op.f('ix_resource_metrics_id'), table_name='resource_metrics')
    op.drop_table('resource_metrics')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_node_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_environment_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_diagnostics_status'), table_name='diagnostics')
    op.drop_index(op.f('ix_diagnostics_severity'), table_name='diagnostics')
    op.drop_index(op.f('ix_diagnostics_node_id'), table_name='diagnostics')
    op.drop_index(op.f('ix_diagnostics_id'), table_name='diagnostics')
    op.drop_index(op.f('ix_diagnostics_diagnosis_type'), table_name='diagnostics')
    op.drop_index(op.f('ix_diagnostics_created_at'), table_name='diagnostics')
    op.drop_table('diagnostics')
    op.drop_index(op.f('ix_capacity_forecasts_node_id'), table_name='capacity_forecasts')
    op.drop_index(op.f('ix_capacity_forecasts_metric_name'), table_name='capacity_forecasts')
    op.drop_index(op.f('ix_capacity_forecasts_id'), table_name='capacity_forecasts')
    op.drop_index(op.f('ix_capacity_forecasts_created_at'), table_name='capacity_forecasts')
    op.drop_table('capacity_forecasts')
    op.drop_index(op.f('ix_agent_tokens_token_hash'), table_name='agent_tokens')
    op.drop_index(op.f('ix_agent_tokens_node_id'), table_name='agent_tokens')
    op.drop_table('agent_tokens')
    op.drop_index(op.f('ix_nodes_status'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_role'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_node_type'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_environment_id'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_environments_status'), table_name='environments')
    op.drop_index(op.f('ix_environments_id'), table_name='environments')
    op.drop_index(op.f('ix_environments_environment_type'), table_name='environments')
    op.drop_table('environments')
    # ### end Alembic commands ###
